### ISSUE TITLE
INFOGRAFÍA DE HILOS

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/infografia-de-hilos-Eva155#2]
[INFOGRAFÍA DE HILOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Eva155/files/6460026/INFOGRAFIA.DE.HILOS.pdf)

**Comment by Abraham890** [comment]
Calificación: 20/20 
Califico: Abraham Reyes Ortiz

**Comment by josealfredo79** [comment]
Bien hecho y revisado

**Comment by josealfredo79** [comment]
Bien hecho y revisado
